### PR TITLE
Allow discovery of hx992s + potentially others, allow integration to start up after home assistant restart

### PR DESCRIPTION
**Pull request by irakhlin**
1. Adding service_uuid and local_name options as discovery in the manifest.json should allow to find most if not all soniccare toothbrushes that are broadcasting. Previous my HX992s would not be discovered by the integration, it is now discovered. Others models should be tested.
2. bluetooth-data-tools must be updated to 0.4.0 for more recent version of home assistant
3. Add SonicareBLETBSensor to additionally inherit from RestoreEntity along with a native_state and assumed_state property. This should resolve the issue of the integration continuously attempting to "reload" and "rediscover" after a restart of home assistant. Previously after restart unless the toothbrush was actively broadcasting (which only happens during use and some short period after) the integration would be continuously in a reloading cycle. With these changes the integration will simply load with the restored sensor values
image

### CODE REVIEW

**Comment by u20p17** [comment]
@GrumpyMeow : Speaks something against merging this pull request? would be nice as this might fix the issue I have with my  HX991B... 👍

**Comment by GrumpyMeow** [comment]
Hi @u20p17,
sorry, sorry, sorry.. I'm a very bad maintainer :-(... I did pickup the manifest.json for discovery of more devices.

**Comment by GrumpyMeow** [comment]
I sort of blindly merged your changes. I will check your changes live. 
Thanks!

**Comment by u20p17** [comment]
> Hi @u20p17, sorry, sorry, sorry.. I'm a very bad maintainer :-(... I did pickup the manifest.json for discovery of more devices.

no problem at all - I am happy that there are people like you who contribute to the community (Y) Thank you for that!

Before the merge HA recognized a sonicare toothbrush (but I couldn't connect). After the merge HA does recognize the toothbrush at all... :( anybody else have this issue?

**Pull request merged**
